# Generated by Django 5.2.3 on 2025-06-30 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FairyCraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapros1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.jewellery')),
            ],
            options={
                'verbose_name': 'Изделия мастера',
                'verbose_name_plural': 'Изделия мастера',
            },
        ),
        migrations.CreateModel(
            name='Zapros2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.jewellery')),
            ],
            options={
                'verbose_name': 'Изделия дороже суммы',
                'verbose_name_plural': 'Изделия дороже суммы',
            },
        ),
        migrations.CreateModel(
            name='Zapros3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.order')),
            ],
            options={
                'verbose_name': 'Заказы клиента',
                'verbose_name_plural': 'Заказы клиента',
            },
        ),
        migrations.CreateModel(
            name='Zapros4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.order')),
            ],
            options={
                'verbose_name': 'Заказы мастера',
                'verbose_name_plural': 'Заказы мастера',
            },
        ),
        migrations.CreateModel(
            name='Zapros5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('jewType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.jewellery_type')),
            ],
            options={
                'verbose_name': 'Заказы по типу изделия',
                'verbose_name_plural': 'Заказы по типу изделия',
            },
        ),
        migrations.CreateModel(
            name='Zapros6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.user')),
            ],
            options={
                'verbose_name': 'Клиенты с суммой заказов выше значения',
                'verbose_name_plural': 'Клиенты с суммой заказов выше значения',
            },
        ),
        migrations.CreateModel(
            name='Zapros7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.jewellery')),
            ],
            options={
                'verbose_name': 'Изделия после года',
                'verbose_name_plural': 'Изделия после года',
            },
        ),
        migrations.CreateModel(
            name='Zapros8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.order')),
            ],
            options={
                'verbose_name': 'Заказы в интервале дат',
                'verbose_name_plural': 'Заказы в интервале дат',
            },
        ),
    ]
