# Generated by Django 5.2.3 on 2025-07-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FairyCraft', '0002_zapros1_zapros2_zapros3_zapros4_zapros5_zapros6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapros9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('metalType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.metall')),
            ],
            options={
                'verbose_name': 'Изделия по материалу',
                'verbose_name_plural': 'Изделия по материалу',
            },
        ),
    ]
