# Generated by Django 5.2.3 on 2025-07-01 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FairyCraft', '0003_zapros9'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapros10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.jewellery_type')),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FairyCraft.user')),
            ],
            options={
                'verbose_name': 'Мастера по типу изделия',
                'verbose_name_plural': 'Мастера по типу изделия',
            },
        ),
    ]
